### ISSUE TITLE
Feature Request: Enable task synchronisation through etesync or similar

### ISSUE THREAD

**Issue by damygdala** [standardnotes/simple-task-editor#74]
I couldn't find anything relating to task syncronisation. I wasn't sure whether this was something that had been decided against for simplicity/security. 

I like the idea of being able to sync tasks (even if it's restricted to viewing them) with another app, that could enable users to associate tasks with alarms/calendars etc. 

Thanks for all of your ongoing work, Standard Notes is an absolute dream.

**Comment by moughxyz** [comment]
Syncing with other apps is a bit out of scope for us. Namely because our server does not deal with unencrypted data, and most syncing between third parties happens on the backend.
